namespace CyConex.Graph
{
    public class LocalNode
    {
        public string nodeID { get; set; }
        public string nodeType { get; set; }
        public string controlBaseScore { get; set; }
        public string controlBaseValue { get; set; }
        public string controlBaseMinValue { get; set; }
        public string controlBaseScoreAssessmentStatus { get; set; }
        public string calculatedValue { get; set; }
        public string controlAssessedValue { get; set; }
        public string controlAssessedScore { get; set; }
        public string controlAssessedMinValue { get; set; }
        public string previouscontrolBaseScore { get; set; }
        public string previousControlAssessedValue { get; set; }
        public string previouscontrolAssessedScore { get; set; }
        public string previousCalculatedValue { get; set; }
        public string objectiveTargetType { get; set; }
        public string objectiveTargetValue { get; set; }
        public string objectiveAcheivedValue { get; set; }
        public string implementedStrength { get; set; }
        public bool enabled { get; set; }
        public string actorCapabilityValue { get; set; }
        public string actorResourcesValue { get; set; }
        public string actorMotivationValue { get; set; }
        public string actorAccessValue { get; set; }
        public string actorScore { get; set; }
        public string actorMitigatedScore { get; set; }
        public string highestAttackActorMitigatedScore { get; set; }
        public string attackComplexityValue { get; set; }
        public string attackProliferationValue { get; set; }
        public string attackScore { get; set; }
        public string attackMitigatedScore { get; set; }
        public string attackImpactToConfidentialityValue { get; set; }
        public string attackImpactToConfidentialityMinValue { get; set; }
        public string attackImpactToIntegrityValue { get; set; }
        public string attackImpactToIntegrityMinValue { get; set; }
        public string attackImpactToAvailabilityValue { get; set; }
        public string attackImpactToAvailabilityMinValue { get; set; }
        public string attackImpactToAccountabilityValue { get; set; }
        public string attackImpactToAccountabilityMinValue { get; set; }
        public string assetConfidentialityValue { get; set; }
        public string assetConfidentialityMinValue { get; set; }
        public string assetConfidentialityProbabilityValue { get; set; }
        public string assetIntegrityValue { get; set; }
        public string assetIntegrityProbabilityValue { get; set; }
        public string assetAvailabilityValue { get; set; }
        public string assetAvailabilityProbabilityValue { get; set; }
        public string assetAccountabilityValue { get; set; }
        public string assetAccountabilityProbabilityValue { get; set; }
        public string assetScore { get; set; }
        public string threatScore { get; set; }
        public string assetLikelihoodScore { get; set; }
        public string assetMitigatedScore { get; set; }
        public string impactScore { get; set; }
        public string riskScore { get; set; }
        public string vulnerabilityEaseOfExploitationValue { get; set; }
        public string vulnerabilityExposureValue { get; set; }
        public string vulnerabilityImpactToConfidentialityValue { get; set; }
        public string vulnerabilityImpactToConfidentialityMinValue { get; set; }
        public string vulnerabilityImpactToIntegrityValue { get; set; }
        public string vulnerabilityImpactToIntegrityMinValue { get; set; }
        public string vulnerabilityImpactToAvailabilityValue { get; set; }
        public string vulnerabilityImpactToAvailabilityMinValue { get; set; }
        public string vulnerabilityImpactToAccountabilityValue { get; set; }
        public string vulnerabilityImpactToAccountabilityMinValue { get; set; }
        public string vulnerabilityExposesScopeValue { get; set; }
        public string vulnerabilityExposesScopeMinValue { get; set; }
        public string vulnerabilityInteractionRequiredValue { get; set; }
        public string vulnerabilityInteractionRequiredMinValue { get; set; }
        public string vulnerabilityPrivilegesRequiredValue { get; set; }
        public string vulnerabilityPrivilegesRequiredMinValue { get; set; }
        public string vulnerabilityScore { get; set; }
        public string vulnerabilityMitigatedScore { get; set; }
        public string likelihoodScore { get; set; }
        public string parent { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string frameworkReference { get; set; }
        public string frameworkName { get; set; }
        public string nodeBehaviour { get; set; }
        public string evidenceValue { get; set; }
        public string actorAccessMinValue { get; set; }
        public string actorCapabilityMinValue { get; set; }
        public string actorResourcesMinValue { get; set; }
        public string actorMotivationMinValue { get; set; }
        public string actorImpactToConfidentialityValue { get; set; }
        public string actorImpactToIntegrityValue { get; set; }
        public string actorImpactToAvailabilityValue { get; set; }
        public string actorImpactToAccountabilityValue { get; set; }
        public string actorImpactToConfidentialityMinValue { get; set; }
        public string actorImpactToIntegrityMinValue { get; set; }
        public string actorImpactToAvailabilityMinValue { get; set; }
        public string actorImpactToAccountabilityMinValue { get; set; }
        public string vulnerabilityEaseOfExploitationMinValue { get; set; }
        public string vulnerabilityExposureMinValue { get; set; }
        public string attackComplexityMinValue { get; set; }
        public string attackProliferationMinValue { get; set; }
        public string assetIntegrityMinValue { get; set; }
        public string assetAvailabilityMinValue { get; set; }
        public string assetAccountabilityMinValue { get; set; }
        public string assetRegulatoryImpactAvailabilityValue { get; set; }
        public string assetReputationalImpactAvailabilityValue { get; set; }
        public string assetFinancialImpactAvailabilityValue { get; set; }
        public string assetPrivacyImpactAccountabilityValue { get; set; }
        public string assetLegalImpactAccountabilityValue { get; set; }
        public string assetRegulatoryImpactAccountabilityValue { get; set; }
        public string assetReputationalImpactAccountabilityValue { get; set; }
        public string assetPrivacyImpactConfidentialityValue { get; set; }
        public string assetLegalImpactConfidentialityValue { get; set; }
        public string assetReputationalImpactConfidentialityValue { get; set; }
        public string assetFinancialImpactConfidentialityValue { get; set; }
        public string assetPrivacyImpactIntegrityValue { get; set; }
        public string assetLegalImpactIntegrityValue { get; set; }
        public string assetRegulatoryImpactIntegrityValue { get; set; }
        public string assetFinancialImpactIntegrityValue { get; set; }
        public string assetPrivacyImpactAvailabilityValue { get; set; }
        public string assetLegalImpactAvailabilityValue { get; set; }
        public string assetRegulatoryImpactConfidentiality { get; set; }
        public string assetReputationalImpactIntegrityValue { get; set; }
        public string assetPrivacyImpactConfidentialityMinValue { get; set; }
        public string assetLegalImpactConfidentialityMinValue { get; set; }
        public string assetRegulatoryImpactConfidentialityValue { get; set; }
        public string assetRegulatoryImpactConfidentialityMinValue { get; set; }
        public string assetReputationalImpactConfidentialityMinValue { get; set; }
        public string assetFinancialImpactConfidentialityMinValue { get; set; }
        public string assetPrivacyImpactIntegrityMinValue { get; set; }
        public string assetLegalImpactIntegrityMinValue { get; set; }
        public string assetRegulatoryImpactIntegrityMinValue { get; set; }
        public string assetReputationalImpactIntegrityMinValue { get; set; }
        public string assetFinancialImpactIntegrityMinValue { get; set; }
        public string assetPrivacyImpactAvailabilityMinValue { get; set; }
        public string assetLegalImpactAvailabilityMinValue { get; set; }
        public string assetRegulatoryImpactAvailabilityMinValue { get; set; }
        public string assetReputationalImpactAvailabilityMinValue { get; set; }
        public string assetFinancialImpactAvailabilityMinValue { get; set; }
        public string assetPrivacyImpactAccountabilityMinValue { get; set; }
        public string assetLegalImpactAccountabilityMinValue { get; set; }
        public string assetRegulatoryImpactAccountabilityMinValue { get; set; }
        public string assetReputationalImpactAccountabilityMinValue { get; set; }
        public string assetFinancialImpactAccountabilityValue { get; set; }
        public string assetFinancialImpactAccountabilityMinValue { get; set; }
        public string controlBaseDistribution { get; set; }
        public string controlAssessedDistribution { get; set; }
        public string actorAccessDistribution { get; set; }
        public string actorCapabilityDistribution { get; set; }
        public string actorResourcesDistribution { get; set; }
        public string actorMotivationDistribution { get; set; }
        public string actorImpactToConfidentialityDistribution { get; set; }
        public string actorImpactToIntegrityDistribution { get; set; }
        public string actorImpactToAvailabilityDistribution { get; set; }
        public string actorImpactToAccountabilityDistribution { get; set; }
        public string vulnerabilityEaseOfExploitationDistribution { get; set; }
        public string vulnerabilityExposesScopeDistribution { get; set; }
        public string vulnerabilityInteractionRequiredDistribution { get; set; }
        public string vulnerabilityPrivilegesRequiredDistribution { get; set; }
        public string vulnerabilityExposureDistribution { get; set; }
        public string vulnerabilityImpactToConfidentialityDistribution { get; set; }
        public string vulnerabilityImpactToIntegrityDistribution { get; set; }
        public string vulnerabilityImpactToAvailabilityDistribution { get; set; }
        public string vulnerabilityImpactToAccountabilityDistribution { get; set; }
        public string attackComplexityDistribution { get; set; }
        public string attackProliferationDistribution { get; set; }
        public string attackImpactToConfidentialityDistribution { get; set; }
        public string attackImpactToIntegrityDistribution { get; set; }
        public string attackImpactToAvailabilityDistribution { get; set; }
        public string attackImpactToAccountabilityDistribution { get; set; }
        public string assetConfidentialityDistribution { get; set; }
        public string assetIntegrityDistribution { get; set; }
        public string assetAvailabilityDistribution { get; set; }
        public string assetAccountabilityDistribution { get; set; }
        public string assetPrivacyImpactConfidentialityDistribution { get; set; }
        public string assetLegalImpactConfidentialityDistribution { get; set; }
        public string assetRegulatoryImpactConfidentialityDistribution { get; set; }
        public string assetReputationalImpactConfidentialityDistribution { get; set; }
        public string assetFinancialImpactConfidentialityDistribution { get; set; }
        public string assetPrivacyImpactIntegrityDistribution { get; set; }
        public string assetLegalImpactIntegrityDistribution { get; set; }
        public string assetReputationalImpactIntegrityDistribution { get; set; }
        public string assetRegulatoryImpactIntegrityDistribution { get; set; }
        public string assetFinancialImpactIntegrityDistribution { get; set; }
        public string assetPrivacyImpactAvailabilityDistribution { get; set; }
        public string assetLegalImpactAvailabilityDistribution { get; set; }
        public string assetRegulatoryImpactAvailabilityDistribution { get; set; }
        public string assetReputationalImpactAvailabilityDistribution { get; set; }
        public string assetFinancialImpactAvailabilityDistribution { get; set; }
        public string assetPrivacyImpactAccountabilityDistribution { get; set; }
        public string assetLegalImpactAccountabilityDistribution { get; set; }
        public string assetRegulatoryImpactAccountabilityDistribution { get; set; }
        public string assetReputationalImpactAccountabilityDistribution { get; set; }
        public string assetFinancialImpactAccountabilityDistribution { get; set; }
        public string assetConfidentialityMitigatedScore { get; set; }
        public string assetIntegrityMitigatedScore { get; set; }
        public string assetAvailabilityMitigatedScore { get; set; }
        public string assetAccountabilityMitigatedScore { get; set; }








    }
}
